### PR TITLE
Added support for multi-node clusters to address issue #16.

### PR DESCRIPTION
**Pull request by ericjsilva**

### CODE REVIEW

**Comment by AndrewFarley** [comment]
Uh @dubiety is there a reason why we can't just always use `"Sum"` so we don't need to add a new variable for this?  :\  Is there something I'm missing?

**Comment by dubiety** [comment]
@AndrewFarley , I think you're right. This variable can be removed. I'll modify it. However, this needs to bump major version since it will be a backward incompatible modification. Will update this week. Thank you for the suggestion.

**Comment by ericjsilva** [comment]
In researching this more, I agree with @AndrewFarley. I made some comments on the [original issue](https://github.com/dubiety/terraform-aws-elasticsearch-cloudwatch-sns-alarms/issues/16#issuecomment-1001597162) I opened as well.

We should add clarity to the readme and variables.

**Comment by AndrewFarley** [comment]
I'll submit an PR for this then shortly @dubiety / @ericjsilva team.

**Pull request merged**
